// All projects data — translated from TypeScript source
const projects = [
  {
    slug: "smartshield-ai",
    title: "SmartShield-AI: Malware Detection",
    oneLiner: "XGBoost malware detection. IJCRT published research.",
    metric: "⚡ 95% Detection Accuracy",
    badge: { label: "PUBLISHED · IJCRT", tone: "gold" },
    tech: ["Python", "XGBoost", "Scikit-learn", "MLflow", "VirusTotal API"],
    categories: ["ML"],
    featured: true, wide: true,
    overview: "End-to-end machine-learning system that classifies Windows PE executables as malicious or benign using static and semi-dynamic analysis. Final-year research project published in IJCRT.",
    problem: "Traditional signature-based antivirus misses novel malware. Detecting unseen Windows binaries requires learning from structural patterns rather than known hashes.",
    solution: "A binary-feature extraction pipeline pulls PE-header metadata, section entropy, and DLL imports from every executable, feeds them through normalization, and trains an XGBoost + Random Forest ensemble. VirusTotal is used as a secondary validation layer; MLflow tracks every run.",
    architecture: ["Raw PE file → static feature extractor (entropy, imports, headers)", "Preprocessing: normalization + scaling, 50+ engineered features", "Ensemble training: XGBoost + Random Forest (compared head-to-head)", "MLflow logs hyperparameters, metrics, model versions", "VirusTotal API used as a secondary verification signal"],
    features: ["Static and semi-dynamic analysis combined", "95% accuracy on MalMem2022, 94% on EMBER / MalwareBazaar", "Fully reproducible experiments via MLflow tracking", "Modular pipeline — swap models or feature sets without rewrites"],
    results: ["95% detection accuracy on MalMem2022", "Research published in IJCRT (Paper ID: IJCRT2603747)", "50+ features tracked and benchmarked"],
    links: [{ label: "Read Paper (IJCRT)", url: "https://ijcrt.org", kind: "research" }],
  },
  {
    slug: "howjis-fashion",
    title: "HOWJIS Fashion",
    oneLiner: "Live e-commerce. Real revenue. Built solo.",
    metric: "📦 30+ Daily Orders",
    badge: { label: "LIVE BUSINESS", tone: "teal" },
    tech: ["WordPress", "WooCommerce", "Payment Gateway", "Instagram Marketing"],
    categories: ["Web", "Backend"],
    featured: true,
    overview: "A production e-commerce store handling real customer transactions, product management, and order fulfilment — built, deployed, and operated solo.",
    problem: "Most student portfolio sites are toy projects. There is a huge gap between writing code and shipping something that real customers actually pay for.",
    solution: "Set up hosting, SSL, domain, WooCommerce catalog, payment gateway, and order workflows from scratch. Drove growth through organic Instagram marketing while handling logistics single-handedly.",
    architecture: ["WordPress + WooCommerce on managed hosting with SSL", "Product catalog with categories, filters, and image galleries", "Integrated payment gateway for online checkout", "Order management, shipping integration, customer notifications"],
    features: ["Catalog, search, filters, product variants", "Online payments and automated order confirmations", "Inventory and shipping management", "Customer communication workflows"],
    results: ["30+ daily orders at peak", "Organic growth via Instagram", "End-to-end ownership: dev, ops, marketing, fulfilment"],
    links: [{ label: "howjisfashion.com", url: "https://howjisfashion.com", kind: "live" }],
  },
  {
    slug: "kaggle-pipelines",
    title: "Kaggle ML Benchmark Pipelines",
    oneLiner: "20+ ML models benchmarked. Reusable pipeline.",
    metric: "🧪 20+ Models Compared",
    badge: { label: "ML RESEARCH", tone: "purple" },
    tech: ["Python", "Scikit-learn", "Pandas", "NumPy"],
    categories: ["ML"],
    featured: true,
    overview: "A pair of public Kaggle notebooks that build systematic, reusable ML pipelines for classification and regression — used to benchmark 20+ models on a single dataset.",
    problem: "Most ML notebooks train one model and call it done. Finding the actually best model for a dataset requires comparing many candidates with consistent preprocessing.",
    solution: "Pipeline objects combine StandardScaler with each model, then run cross-validation across 20+ algorithms (linear, tree-based, boosting) with consistent RMSE / accuracy reporting.",
    architecture: ["Preprocessing: nulls, categorical encoding, feature scaling", "Pipeline = StandardScaler + Model wrapped in sklearn Pipeline", "Models: LR, Ridge, Lasso, SVR, KNN, DT, RF, GBR, XGBoost, ...", "Evaluation: cross-validation + RMSE / R² / accuracy table"],
    features: ["Iris multi-model classification benchmark", "California Housing 20-regressor pipeline", "Reusable structure — swap dataset, get full benchmark"],
    results: ["Two public Kaggle notebooks", "Systematic comparison of 20+ ML models", "Reusable scaffolding for future ML projects"],
    links: [{ label: "kaggle.com/prajwalkedari", url: "https://kaggle.com/prajwalkedari", kind: "kaggle" }],
  },
  {
    slug: "scholarsync",
    title: "ScholarSync",
    oneLiner: "Notes platform used by real college students.",
    metric: "📚 Active College Adoption",
    badge: { label: "REAL USERS", tone: "teal" },
    tech: ["Flask", "Python", "SQLite"],
    categories: ["Web", "Backend"],
    featured: true,
    overview: "A persistent notes-sharing platform built to fix a recurring problem: every semester, students struggle to find notes from previous batches.",
    problem: "At the start of every semester, notes were nowhere to be found — seniors had moved on, and there was no system to preserve material across batches.",
    solution: "Seniors upload notes (text, PDF, images) once. Juniors access them any time, any semester. Notes persist across academic years, organized by subject and semester.",
    architecture: ["Flask backend with SQLite persistence", "File upload (PDF, images, text) with subject/semester metadata", "Auth + role separation (uploader vs reader)", "Cross-semester storage that outlives any single batch"],
    features: ["Multi-format note upload", "Subject + semester + year categorization", "Persistent cross-batch availability", "Student-friendly minimal UI"],
    results: ["Adopted by junior students at Bharat College of Engineering", "Solved a recurring real-world student problem"],
  },
  {
    slug: "wifi-tool",
    title: "WiFi Management Tool",
    oneLiner: "PyPI CLI tool. pip install since 2021.",
    metric: "📦 pip install ready",
    badge: { label: "OPEN SOURCE", tone: "green" },
    tech: ["Python", "Linux", "nmcli", "PyPI"],
    categories: ["Systems", "Automation"],
    featured: true,
    overview: "A command-line WiFi automation tool for Linux and Windows, packaged and published on PyPI as wifimangement-linux.",
    problem: "Managing WiFi networks from the terminal — listing, connecting, retrieving saved credentials — requires remembering different commands per OS.",
    solution: "A unified Python CLI that wraps nmcli (Linux) and netsh (Windows) into one consistent interface, packaged for the global Python community.",
    architecture: ["Python CLI entry point", "OS detection → nmcli (Linux) or netsh (Windows) backend", "Packaged with setuptools, distributed via PyPI"],
    features: ["List available networks", "Connect / disconnect to any network", "Retrieve saved WiFi passwords", "Cross-platform: Linux + Windows"],
    results: ["Published on PyPI (2021)", "Installable globally via pip install wifimangement-linux", "Real open-source contribution to the dev community"],
    links: [{ label: "pypi.org/project/wifimangement-linux", url: "https://pypi.org/project/wifimangement-linux/", kind: "pypi" }],
  },
  {
    slug: "excel-automation",
    title: "Excel Automation Suite",
    oneLiner: "80% workload cut. Runs in live business.",
    metric: "⚙️ 80% Workload Reduced",
    badge: { label: "AUTOMATION", tone: "orange" },
    tech: ["Excel VBA", "SMTP", "WhatsApp API"],
    categories: ["Automation"],
    featured: true,
    overview: "An end-to-end invoicing automation toolkit built in Excel VBA — generates, exports, and delivers customer-specific invoices without a single manual step.",
    problem: "Manual invoice creation, PDF export, and email/WhatsApp delivery was eating hours per week in a real business workflow.",
    solution: "VBA macros generate invoices from customer-specific pricing logic, export to PDF, and dispatch via SMTP email and WhatsApp API on a trigger.",
    architecture: ["Excel workbook with customer + pricing tables", "VBA macros generate dynamic invoice templates", "Auto PDF export from Excel", "SMTP for email, WhatsApp API for messaging"],
    features: ["Customer-specific pricing logic", "Dynamic invoice template generation", "Auto PDF + email + WhatsApp delivery", "Multiple companion tools: tracking, reporting, dashboards"],
    results: ["Reduced manual workload by 80%", "In active daily use in a real business"],
  },
  {
    slug: "disappearmsg",
    title: "DisAppearMsg",
    oneLiner: "Self-destructing messages with one-time view links and TTL.",
    metric: "🔒 Ephemeral by design",
    badge: { label: "BACKEND", tone: "purple" },
    tech: ["Flask", "Python", "SQLite"],
    categories: ["Backend"],
    overview: "Privacy-focused messaging system where messages can only be read once and are automatically deleted after access.",
    problem: "Sharing passwords, OTPs, and sensitive info over chat leaves a permanent trace.",
    solution: "Sender creates a message → unique one-time link → recipient opens → message wiped from DB immediately. Auto-expiry handles links that are never opened.",
    architecture: ["Flask + SQLite", "Token-based one-time view links", "TTL-based scheduled cleanup", "Session-based access control"],
    features: ["One-time view links", "TTL expiry", "Scheduled cleanup", "Session access control"],
    results: ["Working privacy-first ephemeral messaging system"],
  },
  {
    slug: "dream11-predictor",
    title: "Dream11 Fantasy Team Predictor",
    oneLiner: "ML system that auto-generates optimized IPL fantasy teams.",
    metric: "🏏 11-player optimization",
    badge: { label: "ML", tone: "purple" },
    tech: ["Python", "ML", "Data Analytics"],
    categories: ["ML"],
    overview: "Ingests historical player stats, recent form, and match conditions to auto-generate ranked Dream11 IPL fantasy teams.",
    problem: "Picking fantasy teams manually ignores statistical signal in historical data.",
    solution: "Scoring prediction model + statistical optimization for 11-player selection with captain / vice-captain choices.",
    architecture: ["Data ingestion: batting avg, strike rate, bowling economy, recent form", "Scoring prediction model", "Constraint-based 11-player optimization"],
    features: ["Ranked team output", "Captain/VC picks", "Condition-aware scoring"],
    results: ["Automated, data-driven fantasy team selection"],
  },
  {
    slug: "brahmastra-algotrading",
    title: "Brahmastra AlgoTrading",
    oneLiner: "Automated trading signal system using VWAP + Supertrend on live data.",
    metric: "📈 Live market signals",
    badge: { label: "FINANCE", tone: "teal" },
    tech: ["Python", "Yahoo Finance API"],
    categories: ["ML", "Backend"],
    overview: "Algorithmic trading signal engine that pulls real market data and generates buy/sell/hold signals from VWAP and Supertrend.",
    problem: "Manual technical analysis doesn't scale across many tickers in real time.",
    solution: "Fetch historical + live data via Yahoo Finance, compute VWAP and Supertrend, emit signals on indicator crossovers.",
    architecture: ["Yahoo Finance API ingestion", "VWAP + Supertrend computation", "Signal generator on indicator crossovers"],
    features: ["VWAP", "Supertrend", "Buy/sell/hold signal emission"],
    results: ["Working data-driven trading signal pipeline"],
  },
  {
    slug: "attenx-rfid",
    title: "AttenX — RFID Attendance",
    oneLiner: "IoT attendance system using ESP32 + RFID with MySQL backend.",
    metric: "📡 Real-time logging",
    badge: { label: "IOT", tone: "teal" },
    tech: ["ESP32", "C++", "Python", "MySQL"],
    categories: ["IoT", "Systems"],
    overview: "Real-time IoT attendance tracking using RFID cards and ESP32.",
    problem: "Manual attendance is slow and error-prone.",
    solution: "ESP32 reads RFID card → POSTs to Python backend → logs to MySQL → dashboard shows present/absent in real time.",
    architecture: ["ESP32 firmware (C++) reads RFID tag", "HTTP POST to Python backend", "MySQL persistence layer", "Python reporting dashboard"],
    features: ["RFID scan", "Real-time logging", "Reporting dashboard"],
    results: ["End-to-end IoT system: hardware → backend → dashboard"],
  },
  {
    slug: "flash-bank",
    title: "Flash Bank",
    oneLiner: "Full-stack banking simulation with secure transaction logic.",
    metric: "💳 Account + audit logs",
    badge: { label: "BACKEND", tone: "purple" },
    tech: ["Flask", "Python", "MySQL"],
    categories: ["Backend"],
    overview: "Banking simulation system with full account and transaction management.",
    problem: "Designing transactional schemas + secure flows is core backend engineering.",
    solution: "Flask + MySQL app with users, transactions, balances tables and full audit-log style transaction history.",
    architecture: ["Users / Transactions / Balance tables w/ FK relationships", "Auth + session management", "Atomic deposit / withdrawal logic"],
    features: ["Auth", "Deposit / withdrawal", "Real-time balance", "Transaction history"],
    results: ["End-to-end relational + transactional system"],
  },
  {
    slug: "assignment-tracker",
    title: "Assignment Tracker",
    oneLiner: "Cloud-deployed task tracker for academic deadlines.",
    metric: "☁️ Live on PythonAnywhere",
    badge: { label: "WEB", tone: "teal" },
    tech: ["Flask", "Python", "PythonAnywhere"],
    categories: ["Web", "Backend"],
    overview: "Task management system for tracking academic assignments and deadlines.",
    problem: "Local-only tools don't help when you need access from any device.",
    solution: "Cloud-deployed Flask app with auth, deadlines, and overdue tracking.",
    architecture: ["Flask backend", "Persistent storage", "Deployed on PythonAnywhere"],
    features: ["Auth", "Deadlines", "Overdue alerts", "Mobile responsive"],
    results: ["Live cloud deployment with real access"],
  },
  {
    slug: "school-management",
    title: "School Management System",
    oneLiner: "Enterprise admin suite built on .NET / C# / SQL Server.",
    metric: "🏫 Enterprise framework",
    badge: { label: "SYSTEMS", tone: "purple" },
    tech: [".NET", "C#", "SQL Server"],
    categories: ["Systems", "Backend"],
    overview: "Management suite for school administrative operations.",
    problem: "Schools need integrated tooling for records, scheduling, and fees.",
    solution: "Custom .NET architecture covering student records, faculty scheduling, fee tracking, and reports.",
    architecture: [".NET app", "SQL Server data layer", "Module-based feature split"],
    features: ["Student records", "Faculty scheduling", "Fee tracking", "Report generation"],
    results: ["End-to-end admin suite in an enterprise stack"],
  },
  {
    slug: "twitter-sentiment",
    title: "Twitter Sentiment Pipeline",
    oneLiner: "Real-time NLP pipeline classifying tweet sentiment.",
    metric: "🧠 NLP classifier",
    badge: { label: "NLP", tone: "purple" },
    tech: ["Python", "NLTK", "TF-IDF", "Logistic Regression"],
    categories: ["ML", "NLP"],
    overview: "NLP pipeline for classifying tweet sentiment as positive, negative, or neutral.",
    problem: "Raw social text needs preprocessing + feature extraction before any classifier works.",
    solution: "Tokenize → stopword removal → stemming → TF-IDF → Logistic Regression.",
    architecture: ["NLTK preprocessing", "TF-IDF vectorization", "Logistic Regression classifier"],
    features: ["Sentiment classification", "Reusable preprocessing pipeline"],
    results: ["Working sentiment classifier on tweet data"],
  },
  {
    slug: "student-performance",
    title: "Student Performance Prediction",
    oneLiner: "ML system that flags at-risk students from academic indicators.",
    metric: "📊 Early-risk detection",
    badge: { label: "ML", tone: "purple" },
    tech: ["Python", "Scikit-learn", "Matplotlib", "Seaborn"],
    categories: ["ML"],
    overview: "Automated system to identify at-risk students early.",
    problem: "Intervention only works if at-risk students are flagged before exams.",
    solution: "Train classifier on study hours, attendance, and assessment scores; output risk flags.",
    architecture: ["EDA", "Feature engineering", "Classification model", "Risk-flag output"],
    features: ["EDA dashboards", "Risk flagging", "Trend charts"],
    results: ["Working early-risk prediction system"],
  },
  {
    slug: "mu-paper-downloader",
    title: "MU Paper Downloader",
    oneLiner: "Auto-downloads and organizes Mumbai University exam papers.",
    metric: "🗂 Auto file organizer",
    badge: { label: "AUTOMATION", tone: "orange" },
    tech: ["Python"],
    categories: ["Automation"],
    overview: "Automates downloading and organizing MU previous-year exam papers.",
    problem: "Manual paper hunting every exam season wastes hours.",
    solution: "Python scraper + file organizer that builds a clean directory structure.",
    architecture: ["MU portal scraper", "File organizer", "Directory builder"],
    features: ["Auto download", "Subject/year/semester sort", "Consistent naming"],
    results: ["Saves hours every exam season"],
  },
  {
    slug: "library-management",
    title: "Library Management System",
    oneLiner: "PHP + MySQL library catalog with RFID extension.",
    metric: "📚 Catalog + RFID",
    badge: { label: "WEB", tone: "teal" },
    tech: ["PHP", "MySQL", "RFID"],
    categories: ["Web", "IoT"],
    overview: "Database-driven library system with optional RFID hardware integration.",
    problem: "Manual book tracking is slow and error-prone.",
    solution: "Relational schema for catalog + members, with an RFID hardware extension for scan-based borrow/return.",
    architecture: ["PHP backend", "MySQL relational schema", "RFID reader integration in v2"],
    features: ["Cataloging", "Member borrowing cycles", "RFID scan for borrow/return"],
    results: ["End-to-end working system in two iterations (base + RFID)"],
  },
  {
    slug: "jarvis-assistant",
    title: "Jarvis — Voice AI Assistant",
    oneLiner: "Voice-controlled assistant that automates computer tasks.",
    metric: "🎙 Voice automation",
    badge: { label: "AUTOMATION", tone: "orange" },
    tech: ["Python", "speech_recognition", "pyttsx3"],
    categories: ["Automation"],
    overview: "Capstone of CodeWithHarry's 24-Hour Python Course — a voice-controlled AI assistant.",
    problem: "Tying multiple Python libraries together into a single working system.",
    solution: "Speech recognition + text-to-speech + system automation in one Python app.",
    architecture: ["Speech recognition", "TTS responses", "OS-level system control"],
    features: ["Voice commands", "Web search", "App launch", "System control"],
    results: ["Working voice assistant — integration capstone"],
  },
  {
    slug: "t-login",
    title: "T-Login (Termux)",
    oneLiner: "Terminal-based authentication system, debugged without AI.",
    metric: "🐚 Shell scripting",
    badge: { label: "SYSTEMS", tone: "purple" },
    tech: ["Shell Script"],
    categories: ["Systems"],
    overview: "Terminal-based authentication system with full validation logic, built on Termux.",
    problem: "Practicing raw shell scripting without modern AI tooling.",
    solution: "Pure shell-script auth with validation logic, debugged only with StackOverflow.",
    architecture: ["Bash / shell scripts on Termux"],
    features: ["Login flow", "Validation logic", "Terminal-native UX"],
    results: ["Built without AI assistance — pure problem solving"],
  },
  {
    slug: "weather-api",
    title: "Weather API Web Project",
    oneLiner: "First public GitHub Pages project — API-driven weather lookup.",
    metric: "🌤 First public project",
    badge: { label: "WEB", tone: "teal" },
    tech: ["HTML", "JavaScript", "WeatherAPI"],
    categories: ["Web"],
    overview: "Fetches weather of any city using WeatherAPI — first public GitHub Pages project (July 2022).",
    problem: "Learning async API integration in vanilla JS.",
    solution: "Vanilla JS app with async fetch to WeatherAPI.",
    architecture: ["HTML + JS", "Async fetch", "GitHub Pages deploy"],
    features: ["City search", "Live weather data"],
    results: ["First deployed public project"],
    links: [{ label: "prajwalkedari.github.io/weather-api", url: "https://prajwalkedari.github.io/weather-api", kind: "live" }],
  },
  {
    slug: "flash-bank-flask",
    title: "Flash Bank (Flask variant)",
    oneLiner: "Iterated Flask + MySQL banking app with stronger schema design.",
    metric: "🧾 Relational schema",
    badge: { label: "BACKEND", tone: "purple" },
    tech: ["Flask", "Python", "MySQL"],
    categories: ["Backend"],
    overview: "Second-iteration Flask banking app focused on cleaner schema and transaction logic.",
    problem: "First version exposed schema design gaps — needed iteration.",
    solution: "Redesigned relational schema, tightened transaction flow, improved auth.",
    architecture: ["Flask", "MySQL", "Cleaner FK relationships"],
    features: ["Auth", "Deposit/withdraw", "Audit log"],
    results: ["Iteration that strengthened backend fundamentals"],
  },
];

const featuredProjects = projects.filter(p => p.featured);

function getProject(slug) {
  return projects.find(p => p.slug === slug);
}
